// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDysEqM17JuabYAGVsh8Yv5rSZPlwThw',
    appId: '1:105790147696:web:f9f1f409824e7abfc638b5',
    messagingSenderId: '105790147696',
    projectId: 'drugreminder-e8c48',
    authDomain: 'drugreminder-e8c48.firebaseapp.com',
    storageBucket: 'drugreminder-e8c48.appspot.com',
    measurementId: 'G-17GMNY9GMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHKOywmi5yoryWY2xLeoARlBB2VY8VeA',
    appId: '1:105790147696:android:a5f8996a06068218c638b5',
    messagingSenderId: '105790147696',
    projectId: 'drugreminder-e8c48',
    storageBucket: 'drugreminder-e8c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKe0or43Ge2U-TQAxeptc2ZRbptbgGxg',
    appId: '1:105790147696:ios:6408df875aabc6eec638b5',
    messagingSenderId: '105790147696',
    projectId: 'drugreminder-e8c48',
    storageBucket: 'drugreminder-e8c48.appspot.com',
    iosClientId:
        '105790147696-flqp3nckkuieq4cnsuvtam199ld589c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.drugReminder',
  );
}
